package com.cryptoanalytic.domain.entity.cryptocurrencyDetails


data class MarketData(
    val ath: Ath,
    val ath_change_percentage: PriceChangePercentageInCurrency,
    val ath_date: AthDate,
    val atl: PriceChangePercentageInCurrency,
    val atl_change_percentage: PriceChangePercentageInCurrency,
    val atl_date: AtlDate,
    val circulating_supply: Double,
    val current_price: CurrentPrice,
    val fdv_to_tvl_ratio: Any,
    val fully_diluted_valuation: FullyDilutedValuation,
    val high_24h: High24h,
    val last_updated: String,
    val low_24h: Low24h,
    val market_cap: MarketCap,
    val market_cap_change_24h: Double,
    val market_cap_change_24h_in_currency: PriceChangePercentageInCurrency,
    val market_cap_change_percentage_24h: Double,
    val market_cap_change_percentage_24h_in_currency: PriceChangePercentageInCurrency,
    val market_cap_rank: Int,
    val max_supply: Double,
    val mcap_to_tvl_ratio: Any,
    val price_change_24h: Double,
    val price_change_24h_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_14d: Double,
    val price_change_percentage_14d_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_1h_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_1y: Double,
    val price_change_percentage_1y_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_200d: Double,
    val price_change_percentage_200d_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_24h: Double,
    val price_change_percentage_24h_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_30d: Double,
    val price_change_percentage_30d_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_60d: Double,
    val price_change_percentage_60d_in_currency: PriceChangePercentageInCurrency,
    val price_change_percentage_7d: Double,
    val price_change_percentage_7d_in_currency: PriceChangePercentageInCurrency,
    val roi: Any,
    val total_supply: Double,
    val total_value_locked: Any,
    val total_volume: TotalVolume
)